// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FindAFixMVCCodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// A technician logs in, sends a proposal for a job and logs out
        /// </summary>
        public void TechLoginTakeJobLogout()
        {
            #region Variable Declarations
            WinEdit uILoginEdit = this.UIFindAFixMozillaFirefWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIEmailEdit = this.UIFindAFixMozillaFirefWindow.UILoginFindAFixDocument.UIEmailEdit;
            WinListItem uINewtechtechcomListItem = this.UIItemWindow.UIItemList.UINewtechtechcomListItem;
            WinButton uILoginButton = this.UIFindAFixMozillaFirefWindow.UILoginFindAFixDocument.UILoginButton;
            WinEdit uIAvailableJobsEdit = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsHyperlink.UIAvailableJobsEdit;
            WinEdit uITakeEdit = this.UIFindAFixMozillaFirefWindow.UITakeHyperlink.UITakeEdit;
            WinEdit uIPriceEstEdit = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsFindAFiDocument.UIPriceEstEdit;
            WinCustom uIItemCustom = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsFindAFiDocument.UIItemCustom;
            WinEdit uIMessageEdit = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsFindAFiDocument.UIMessageEdit;
            WinEdit uIAvailabilityDateEdit = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsFindAFiDocument.UIAvailabilityDateEdit;
            WinButton uISendButton = this.UIFindAFixMozillaFirefWindow.UIAvailableJobsFindAFiDocument.UISendButton;
            WinEdit uILogoffEdit = this.UIFindAFixMozillaFirefWindow.UILogoffHyperlink.UILogoffEdit;
            #endregion

            // Click 'Log in' text box
            Mouse.Click(uILoginEdit, new Point(23, 14));

            // Type 'newte' in 'Email' text box
            uIEmailEdit.Text = this.TechLoginTakeJobLogoutParams.UIEmailEditText;

            // Click 'newtech@tech.com' list item
            Mouse.Click(uINewtechtechcomListItem, new Point(100, 3));

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(73, 29));

            // Click 'Available Jobs' text box
            Mouse.Click(uIAvailableJobsEdit, new Point(73, 23));

            // Click 'Take' text box
            Mouse.Click(uITakeEdit, new Point(12, 0));

            // Type '99.99' in 'PriceEst' text box
            uIPriceEstEdit.Text = this.TechLoginTakeJobLogoutParams.UIPriceEstEditText;

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(533, 13));

            // Type 'I can do it' in 'Message' text box
            uIMessageEdit.Text = this.TechLoginTakeJobLogoutParams.UIMessageEditText;

            // Type '2016-12-22' in 'AvailabilityDate' text box
            uIAvailabilityDateEdit.Text = this.TechLoginTakeJobLogoutParams.UIAvailabilityDateEditText;

            // Click 'Send' button
            Mouse.Click(uISendButton, new Point(26, 24));

            // Click 'Log off' text box
            Mouse.Click(uILogoffEdit, new Point(21, 20));
        }
        
        #region Properties
        public virtual TechLoginTakeJobLogoutParams TechLoginTakeJobLogoutParams
        {
            get
            {
                if ((this.mTechLoginTakeJobLogoutParams == null))
                {
                    this.mTechLoginTakeJobLogoutParams = new TechLoginTakeJobLogoutParams();
                }
                return this.mTechLoginTakeJobLogoutParams;
            }
        }
        
        public UIFindAFixMozillaFirefWindow UIFindAFixMozillaFirefWindow
        {
            get
            {
                if ((this.mUIFindAFixMozillaFirefWindow == null))
                {
                    this.mUIFindAFixMozillaFirefWindow = new UIFindAFixMozillaFirefWindow();
                }
                return this.mUIFindAFixMozillaFirefWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private TechLoginTakeJobLogoutParams mTechLoginTakeJobLogoutParams;
        
        private UIFindAFixMozillaFirefWindow mUIFindAFixMozillaFirefWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TechLoginTakeJobLogout'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TechLoginTakeJobLogoutParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'newte' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "newte";
        
        /// <summary>
        /// Type '99.99' in 'PriceEst' text box
        /// </summary>
        public string UIPriceEstEditText = "99.99";
        
        /// <summary>
        /// Type 'I can do it' in 'Message' text box
        /// </summary>
        public string UIMessageEditText = "I can do it";
        
        /// <summary>
        /// Type '2016-12-22' in 'AvailabilityDate' text box
        /// </summary>
        public string UIAvailabilityDateEditText = "2016-12-22";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFindAFixMozillaFirefWindow : WinWindow
    {
        
        public UIFindAFixMozillaFirefWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "- Find A Fix - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("- Find A Fix - Mozilla Firefox");
            this.WindowTitles.Add("Log in - Find A Fix - Mozilla Firefox");
            this.WindowTitles.Add("View - Find A Fix - Mozilla Firefox");
            this.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UILoginHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new UILoginHyperlink(this);
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public UILoginFindAFixDocument UILoginFindAFixDocument
        {
            get
            {
                if ((this.mUILoginFindAFixDocument == null))
                {
                    this.mUILoginFindAFixDocument = new UILoginFindAFixDocument(this);
                }
                return this.mUILoginFindAFixDocument;
            }
        }
        
        public UIAvailableJobsHyperlink UIAvailableJobsHyperlink
        {
            get
            {
                if ((this.mUIAvailableJobsHyperlink == null))
                {
                    this.mUIAvailableJobsHyperlink = new UIAvailableJobsHyperlink(this);
                }
                return this.mUIAvailableJobsHyperlink;
            }
        }
        
        public UITakeHyperlink UITakeHyperlink
        {
            get
            {
                if ((this.mUITakeHyperlink == null))
                {
                    this.mUITakeHyperlink = new UITakeHyperlink(this);
                }
                return this.mUITakeHyperlink;
            }
        }
        
        public UIAvailableJobsFindAFiDocument UIAvailableJobsFindAFiDocument
        {
            get
            {
                if ((this.mUIAvailableJobsFindAFiDocument == null))
                {
                    this.mUIAvailableJobsFindAFiDocument = new UIAvailableJobsFindAFiDocument(this);
                }
                return this.mUIAvailableJobsFindAFiDocument;
            }
        }
        
        public UILogoffHyperlink UILogoffHyperlink
        {
            get
            {
                if ((this.mUILogoffHyperlink == null))
                {
                    this.mUILogoffHyperlink = new UILogoffHyperlink(this);
                }
                return this.mUILogoffHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UILoginHyperlink mUILoginHyperlink;
        
        private UILoginFindAFixDocument mUILoginFindAFixDocument;
        
        private UIAvailableJobsHyperlink mUIAvailableJobsHyperlink;
        
        private UITakeHyperlink mUITakeHyperlink;
        
        private UIAvailableJobsFindAFiDocument mUIAvailableJobsFindAFiDocument;
        
        private UILogoffHyperlink mUILogoffHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginHyperlink : WinHyperlink
    {
        
        public UILoginHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Log in";
            this.WindowTitles.Add("- Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Log in";
                    this.mUILoginEdit.WindowTitles.Add("- Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginFindAFixDocument : WinControl
    {
        
        public UILoginFindAFixDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log in - Find A Fix";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Log in - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.WindowTitles.Add("Log in - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Log in";
                    this.mUILoginButton.WindowTitles.Add("Log in - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEmailEdit;
        
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAvailableJobsHyperlink : WinHyperlink
    {
        
        public UIAvailableJobsHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Available Jobs";
            this.WindowTitles.Add("View - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAvailableJobsEdit
        {
            get
            {
                if ((this.mUIAvailableJobsEdit == null))
                {
                    this.mUIAvailableJobsEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAvailableJobsEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Available Jobs";
                    this.mUIAvailableJobsEdit.WindowTitles.Add("View - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIAvailableJobsEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAvailableJobsEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITakeHyperlink : WinHyperlink
    {
        
        public UITakeHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Take";
            this.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UITakeEdit
        {
            get
            {
                if ((this.mUITakeEdit == null))
                {
                    this.mUITakeEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITakeEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Take";
                    this.mUITakeEdit.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUITakeEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITakeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAvailableJobsFindAFiDocument : WinControl
    {
        
        public UIAvailableJobsFindAFiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Available Jobs - Find A Fix";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPriceEstEdit
        {
            get
            {
                if ((this.mUIPriceEstEdit == null))
                {
                    this.mUIPriceEstEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPriceEstEdit.SearchProperties[WinEdit.PropertyNames.Name] = "PriceEst";
                    this.mUIPriceEstEdit.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIPriceEstEdit;
            }
        }
        
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinEdit UIMessageEdit
        {
            get
            {
                if ((this.mUIMessageEdit == null))
                {
                    this.mUIMessageEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIMessageEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Message";
                    this.mUIMessageEdit.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIMessageEdit;
            }
        }
        
        public WinEdit UIAvailabilityDateEdit
        {
            get
            {
                if ((this.mUIAvailabilityDateEdit == null))
                {
                    this.mUIAvailabilityDateEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAvailabilityDateEdit.SearchProperties[WinEdit.PropertyNames.Name] = "AvailabilityDate";
                    this.mUIAvailabilityDateEdit.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUIAvailabilityDateEdit;
            }
        }
        
        public WinButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WinButton.PropertyNames.Name] = "Send";
                    this.mUISendButton.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPriceEstEdit;
        
        private WinCustom mUIItemCustom;
        
        private WinEdit mUIMessageEdit;
        
        private WinEdit mUIAvailabilityDateEdit;
        
        private WinButton mUISendButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogoffHyperlink : WinHyperlink
    {
        
        public UILogoffHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Log off";
            this.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILogoffEdit
        {
            get
            {
                if ((this.mUILogoffEdit == null))
                {
                    this.mUILogoffEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILogoffEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Log off";
                    this.mUILogoffEdit.WindowTitles.Add("Available Jobs - Find A Fix - Mozilla Firefox");
                    #endregion
                }
                return this.mUILogoffEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILogoffEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Log in - Find A Fix - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinListItem UINewtechtechcomListItem
        {
            get
            {
                if ((this.mUINewtechtechcomListItem == null))
                {
                    this.mUINewtechtechcomListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUINewtechtechcomListItem.SearchProperties[WinListItem.PropertyNames.Name] = "newtech@tech.com";
                    #endregion
                }
                return this.mUINewtechtechcomListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUINewtechtechcomListItem;
        #endregion
    }
}
